// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

var findTheDifference = function(s, t) {
    // change the strings into arrays of strings and sort them in alphabetical order
    let arrOfS = s.split("").sort();
    let arrOfT = t.split("").sort();

    // loop through the longer of the two strings and see if the indexed string is the same in both new arrays, if not, return that element
    for (let i=0; i<arrOfT.length; i++) {
        if (arrOfT[i] !== arrOfS[i]) {
            return arrOfT[i]
        }
    }
};

// given two strings (s) and (t) where t is s with the substrings shuffled and one substring added at a random place in the string
// return the substring that is in t and not in s
// console.log(findTheDifference("abcd", "abcde"); "e");
// console.log(findTheDifference("", "y"); "y");